### ISSUE TITLE
Peek providers/consumers doesn't work for service names containing a number

### ISSUE THREAD

**Issue by anticultist** [ctjdr/vscode-apprt-bundles#56]
**Describe the bug**
Code lens "Peak providers" and "Peak consumers" doesn't work when the name contains a minus sign although the code lens shows that the number of references is greater than zero.

**To Reproduce**
1. Go to a `manifest.json` file
2. Click on 'Peek consumers' or 'Peek providers' code lense where the name contains a minus sign e.g. `measurement-2d.CreateMeasurementToolHandler`

**Expected behavior**
Opens the reference view.

**Actual behavior**
Info message appears with the following text `No references found for 'measurement'` for a fraction of a second.

**Additional context**
The code lens seems to find the references at first. But on showing the references seems to be an issue.

**Comment by anticultist** [comment]
Maybe the bug is not triggered by the minus sign but by the number because the code lens works for names like `map-widget.MapWidgetFactory`.

**Comment by ctjdr** [comment]
Can reproduce it with a test project. Thank you for reporting the issue!
